name: "🐛 Bug Report: API Field Missing"
description: Report a problem where existing API Endpoints have missing fields but available in Highlevel UI
title: "[Bug Report: API Field Missing] "
labels: ["bug-missing-api-field"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## Thank you for reporting missing API fields!
        
        Please fill out the information below to help us address the missing field issue quickly.

  - type: textarea
    id: bug-description
    attributes:
      label: 🐛 Describe the Bug
      description: A clear and concise description of what the bug is.
      placeholder: The API endpoint is missing field X which is available in the Highlevel UI...
    validations:
      required: true

  - type: input
    id: api-endpoint
    attributes:
      label: 📍 API Endpoint
      description: Which API endpoint does this relate to?
      placeholder: e.g., /api/v2/users/{id}
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: ✅ Expected Behavior
      description: What should have happened?
      placeholder: The API should return field X with value Y...
    validations:
      required: true

  - type: textarea
    id: code-samples
    attributes:
      label: 💻 Screenshots or Code Samples
      description: Paste relevant markdown/code samples or screenshots.
      placeholder: |
        ```json
        {
          "missing_field": "should_be_here"
        }
        ```
    validations:
      required: false
      
  - type: dropdown
    id: product-area
    attributes:
      label: Product Area
      description: Which product area does this issue relate to?
      options:
        - wordpress
        - saas
        - lc-phone
        - lc-whatsapp
        - lc-phone-sms
        - lc-phone-voice
        - membership
        - client-portal
        - prospecting
        - reputation
        - gatekeeper
        - yext
        - communities
        - snapshots
        - blade-platform
        - lc-email
        - internal-tools
        - reselling
        - gokollab
        - certificates
        - assets-drm
        - funnels
        - launchpad
        - forms
        - surveys
        - blogs
        - emails
        - onboarding
        - payments
        - payment-products
        - payments-core
        - platform-ui
        - proposals
        - social-planner
        - templates
        - cm-webshot
        - cm-medias
        - cm-es-logger
        - cm-ts
        - common.*
        - ecomm-store
        - contacts
        - conversations
        - marketplace
        - conversations-ai
        - bulk-actions
        - custom-objects
        - opportunities
        - integrations
        - cdp
        - marketplace-modules
        - data
        - services
        - infra
        - am
        - reporting
        - calendars
        - eliza
        - workflows
        - ad-publishing
        - bi
        - backend
        - voice
        - text
        - highly
        - support
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: 🧠 Additional Context
      description: Any other helpful information?
      placeholder: This field is also missing in other related endpoints...
    validations:
      required: false 