name: "🌟 Feature Request: New APIs"
description: Suggest a new feature or documentation improvement
title: "[Feature New API] "
labels: ["feature-request"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## Thank you for suggesting a new API feature!
        
        Please fill out the information below to help us understand your feature request.

  - type: textarea
    id: feature-description
    attributes:
      label: 🌟 Describe the Feature
      description: A clear and concise description of the proposed improvement.
      placeholder: I would like to see an API endpoint that can...
    validations:
      required: true

  - type: textarea
    id: justification
    attributes:
      label: 🚀 Justification
      description: Why would this be useful for other developers?
      placeholder: This would help developers by...
    validations:
      required: true

  - type: textarea
    id: suggestions
    attributes:
      label: 📝 Suggestions
      description: If applicable, include ideas or mockups of the improvement.
      placeholder: |
        ```json
        {
          "suggested_endpoint": "/api/v2/new-feature",
          "method": "POST",
          "response": "..."
        }
        ```
    validations:
      required: false
      
  - type: dropdown
    id: product-area
    attributes:
      label: Product Area
      description: Which product area would this new API relate to?
      options:
        - wordpress
        - saas
        - lc-phone
        - lc-whatsapp
        - lc-phone-sms
        - lc-phone-voice
        - membership
        - client-portal
        - prospecting
        - reputation
        - gatekeeper
        - yext
        - communities
        - snapshots
        - blade-platform
        - lc-email
        - internal-tools
        - reselling
        - gokollab
        - certificates
        - assets-drm
        - funnels
        - launchpad
        - forms
        - surveys
        - blogs
        - emails
        - onboarding
        - payments
        - payment-products
        - payments-core
        - platform-ui
        - proposals
        - social-planner
        - templates
        - cm-webshot
        - cm-medias
        - cm-es-logger
        - cm-ts
        - common.*
        - ecomm-store
        - contacts
        - conversations
        - marketplace
        - conversations-ai
        - bulk-actions
        - custom-objects
        - opportunities
        - integrations
        - cdp
        - marketplace-modules
        - data
        - services
        - infra
        - am
        - reporting
        - calendars
        - eliza
        - workflows
        - ad-publishing
        - bi
        - backend
        - voice
        - text
        - highly
        - support
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: 🧠 Additional Context
      description: Any other details you'd like to share?
      placeholder: This feature would integrate well with...
    validations:
      required: false 